services:
  app:
    image: ${DOCKER_IMAGE}:${VERSION}
    container_name: ${DOCKER_CONTAINER_NAME}
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - JWT_SECRET=${JWT_SECRET}
      - VERSION=${VERSION}
      - MEDIA_BASE_URL=${MEDIA_BASE_URL}
      - UPLOAD_PATH=/app/public/media
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
    volumes:
      - media_data:/app/public/media
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - smashtravelvietnam-be-network

  db:
    image: postgres:15
    container_name: smashtravelvietnam_postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - smashtravelvietnam-be-network

volumes:
  postgres_data:
  media_data:
    driver: local
    driver_opts:
      type: none
      device: /opt/apps/media/smashtravelvietnam.com
      o: bind

networks:
  smashtravelvietnam-be-network:
    driver: bridge
  vinaup-docker-network:
    external: true
